"""Add urgency and summary to tickets

Revision ID: 537c0761e4c9
Revises: 5ba05a96ad54
Create Date: 2026-08-05 16:24:08.022695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537c0761e4c9'
down_revision: Union[str, Sequence[str], None] = '5ba05a96ad54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('urgency', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'summary')
    op.drop_column('tickets', 'urgency')
    # ### end Alembic commands ###
