"""Add reporter details to tickets

Revision ID: be8ffe35dfd2
Revises: 537c0761e4c9
Create Date: 2026-08-05 16:31:27.626356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8ffe35dfd2'
down_revision: Union[str, Sequence[str], None] = '537c0761e4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('reporter_name', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('reporter_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'reporter_email')
    op.drop_column('tickets', 'reporter_name')
    # ### end Alembic commands ###
